Allow use of guzzlehttp/psr7:^2.0
ratchetphp/Pawl pull request #126
Opened 2021-08-03 14:27 UTC by mbabker

This PR does two things:

1) Declares the dependency to `guzzlehttp/psr7` which was previously installed as a transient dependency
2) Updates the `Connector` class to avoid use of the deprecated functions from that package, this requires bumping the minimum supported `guzzlehttp/psr7` version up to 1.7 (when the replacements were introduced) and will allow use of the new 2.0 release

2021-10-03 14:58 UTC, SergeC commented
Can we get it merged? CC https://github.com/ratchetphp/Pawl/issues/132

2021-12-01 14:57 UTC, erikn69 commented
https://github.com/ratchetphp/RFC6455/pull/47
are RatchetPhp repositories abandoned?

2021-12-10 00:05 UTC, cboden requested changes

2021-12-10 00:05 UTC, cboden commented on composer.json
>        , "ratchet/rfc6455": "^0.3"
```suggestion
      , "ratchet/rfc6455": "^0.3.1"
```

2021-12-10 00:06 UTC, cboden commented
Pros/Cons on specifying guzzle/psr versions verses implicitly accepting what rfc6455 requires?

2021-12-10 01:26 UTC, mbabker commented
As this package is directly dependent on the `guzzlehttp/psr7` package, it should explicitly declare its dependency.  Relying on transient dependencies to install your direct dependencies is never a good idea.

2021-12-10 14:29 UTC, cboden approved these changes

2021-12-10 14:30 UTC, merged